"""CPU training presets — tuned for VPS without GPU."""

from app.services.training.cpu_tuning import tune_training_config

CPU_PRESETS: dict[str, dict] = {
    "ultimate_accuracy": {
        "label": "Ultimate Accuracy",
        "description": "40 epochs · 640px · medium aug · frozen backbone — maximum mAP on CPU VPS",
        "epochs": 40,
        "batch_size": 12,
        "learning_rate": 0.0008,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "medium",
        "image_size": 640,
        "mixed_precision": False,
        "val_split": 0.12,
        "cache": True,
        "prefer_disk_cache": True,
        "patience": 20,
        "close_mosaic": 10,
        "warmup_epochs": 4,
        "freeze_layers": 10,
        "label_smoothing": 0.05,
        "workers": "auto",
        "device": "cpu",
        "fine_tune_from_active": True,
    },
    "fine_tune": {
        "label": "Fine-tune Main Model",
        "description": "30 epochs · 640px · low LR — continues from active Main Model (best mAP gain)",
        "epochs": 30,
        "batch_size": 8,
        "learning_rate": 0.001,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "light",
        "image_size": 640,
        "mixed_precision": False,
        "val_split": 0.15,
        "cache": True,
        "prefer_disk_cache": True,
        "patience": 15,
        "close_mosaic": 5,
        "warmup_epochs": 3,
        "workers": "auto",
        "device": "cpu",
        "fine_tune_from_active": True,
    },
    "best_accuracy": {
        "label": "Best Accuracy",
        "description": "20 epochs · 640px · medium aug — highest mAP on CPU VPS (recommended)",
        "epochs": 20,
        "batch_size": 8,
        "learning_rate": 0.01,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "medium",
        "image_size": 640,
        "mixed_precision": False,
        "val_split": 0.15,
        "cache": True,
        "prefer_disk_cache": True,
        "patience": 10,
        "close_mosaic": 3,
        "workers": "auto",
        "device": "cpu",
        "fine_tune_from_active": True,
    },
    "max_cpu": {
        "label": "Max CPU",
        "description": "Uses all CPU cores · auto batch · disk cache — fastest full training",
        "epochs": 12,
        "batch_size": "auto",
        "learning_rate": 0.01,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "light",
        "image_size": 416,
        "mixed_precision": False,
        "val_split": 0.15,
        "cache": True,
        "prefer_disk_cache": True,
        "patience": 6,
        "close_mosaic": 2,
        "workers": "auto",
        "device": "cpu",
    },
    "fleet_cpu": {
        "label": "Fleet Camera",
        "description": "12 epochs · 416px · tuned for live road detection on CPU",
        "epochs": 12,
        "batch_size": 14,
        "learning_rate": 0.01,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "light",
        "image_size": 416,
        "mixed_precision": False,
        "val_split": 0.15,
        "cache": True,
        "patience": 6,
        "close_mosaic": 2,
        "workers": "auto",
        "device": "cpu",
    },
    "turbo_cpu": {
        "label": "Turbo CPU",
        "description": "5 epochs · 320px · minimal aug — fastest run for quick tests",
        "epochs": 5,
        "batch_size": 16,
        "learning_rate": 0.01,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "none",
        "image_size": 320,
        "mixed_precision": False,
        "val_split": 0.15,
        "cache": True,
        "patience": 3,
        "close_mosaic": 2,
        "workers": "auto",
        "device": "cpu",
    },
    "fast_cpu": {
        "label": "Fast CPU",
        "description": "8 epochs · 416px · light augmentation — recommended on CPU VPS",
        "epochs": 8,
        "batch_size": 12,
        "learning_rate": 0.01,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "light",
        "image_size": 416,
        "mixed_precision": False,
        "val_split": 0.2,
        "cache": True,
        "patience": 5,
        "close_mosaic": 3,
        "workers": "auto",
        "device": "cpu",
    },
    "balanced": {
        "label": "Balanced CPU",
        "description": "15 epochs · 640px · medium augmentation — better accuracy, slower",
        "epochs": 15,
        "batch_size": 8,
        "learning_rate": 0.01,
        "optimizer": "AdamW",
        "scheduler": "cosine",
        "augmentation": "medium",
        "image_size": 640,
        "mixed_precision": False,
        "val_split": 0.2,
        "cache": True,
        "patience": 8,
        "workers": "auto",
        "device": "cpu",
    },
}

DEFAULT_CPU_PRESET = "ultimate_accuracy"


def build_retrain_config(
    epochs: int | None,
    preset: str = DEFAULT_CPU_PRESET,
    *,
    fine_tune_from_active: bool | None = None,
) -> dict:
    from app.services.training.cpu_tuning import QUALITY_PRESETS

    base = dict(CPU_PRESETS.get(preset, CPU_PRESETS[DEFAULT_CPU_PRESET]))
    if epochs is not None:
        base["epochs"] = epochs
    base["_preset"] = preset
    base["_prioritize_accuracy"] = preset in QUALITY_PRESETS
    base["continuous"] = True
    if fine_tune_from_active is not None:
        base["fine_tune_from_active"] = fine_tune_from_active
    elif "fine_tune_from_active" not in base:
        base["fine_tune_from_active"] = True
    from app.services.training.fine_tune import apply_fine_tune_training_overrides

    return tune_training_config(apply_fine_tune_training_overrides(base))
